version: '3'

services:
  postgres_blog:
    container_name: postgres_blog
    image: bitnami/postgresql:latest
    ports:
      - '5000:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=blog
    volumes:
      - blog_pg_data:/bitnami/postgresql

  redis_blog:
    container_name: redis_blog
    image: redis
    ports:
      - '6379:6379'

  # username: guest e password: guest  
  rabbitmq_blog:
    container_name: rabbitmq_blog
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
  
  jaeger:
    container_name: jaeger_blog
    image: jaegertracing/opentelemetry-all-in-one
    ports:
      - '4317:4317'
      - '13133:13133'
      - '16686:16686'

volumes:
  blog_pg_data:
